(() => {
  "use strict";
  const KEY = "ai-tools-day04-customers-v1";
  const DEMO = [
    { id: "demo-1", name: "李总", company: "远航制造", need: "采购生产线服务器", budget: "30万元左右", status: "需求确认", feedback: "下周要确定供应商，希望了解交付周期。", lastContact: 1, intent: 5 },
    { id: "demo-2", name: "张总", company: "XX科技", need: "采购服务器", budget: "20万元左右", status: "已报价", feedback: "价格有点高，再考虑一下。", lastContact: 5, intent: 4 },
    { id: "demo-3", name: "王总", company: "星河软件", need: "企业存储升级", budget: "待确认", status: "无回复", feedback: "已发送方案，暂未回复。", lastContact: 12, intent: 3 },
    { id: "demo-4", name: "陈总", company: "新锐传媒", need: "了解云服务", budget: "5万元左右", status: "待联系", feedback: "刚加微信，还没有深入沟通。", lastContact: 0, intent: 2 },
    { id: "demo-5", name: "赵经理", company: "启明医疗", need: "机房改造", budget: "80万元左右", status: "谈判中", feedback: "正在比较两家供应商，关注售后。", lastContact: 3, intent: 4 }
  ];
  const $ = (s) => document.querySelector(s);
  const els = { list: $("#customerList"), search: $("#searchInput"), sort: $("#sortSelect"), detail: $("#detailContent"), empty: $("#emptyDetail"), toast: $("#toast"), saveState: $("#saveState") };
  let customers = load(); let selectedId = customers[0]?.id || null; let toastTimer;
  function load() { try { const saved = JSON.parse(localStorage.getItem(KEY)); return Array.isArray(saved) ? saved : []; } catch { return []; } }
  function save() { localStorage.setItem(KEY, JSON.stringify(customers)); els.saveState.textContent = `已保存 ${new Date().toLocaleTimeString("zh-CN", {hour:"2-digit", minute:"2-digit"})}`; }
  function id() { return `c-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
  function toast(message, error = false) { clearTimeout(toastTimer); els.toast.textContent = message; els.toast.className = `toast show${error ? " error" : ""}`; toastTimer = setTimeout(() => els.toast.className = "toast", 2800); }
  function score(c) { let s = 0; s += Number(c.intent || 1) * 10; s += Math.min(Number(c.lastContact || 0), 30); const map = { "需求确认":18, "已报价":16, "谈判中":20, "无回复":14, "待联系":5, "已成交":-20, "已流失":-30 }; s += map[c.status] || 0; return Math.max(0, Math.min(100, s)); }
  function level(s) { return s >= 60 ? "high" : s >= 40 ? "medium" : "low"; }
  function priority(s) { return s >= 60 ? "高优先级" : s >= 40 ? "中优先级" : "低优先级"; }
  function stars(n) { const x = Number(n || 1); return "★".repeat(x) + "☆".repeat(5 - x); }
  function visible() { const q = els.search.value.trim().toLowerCase(); const arr = customers.filter(c => !q || [c.name,c.company,c.need,c.status,c.feedback].join(" ").toLowerCase().includes(q)); const type = els.sort.value; return arr.sort((a,b) => type === "priority" ? score(b)-score(a) : type === "recent" ? Number(b.lastContact)-Number(a.lastContact) : type === "intent" ? Number(b.intent)-Number(a.intent) : a.name.localeCompare(b.name,"zh-CN")); }
  function renderMetrics() { $("#totalCount").textContent = customers.length; $("#priorityCount").textContent = customers.filter(c => score(c) >= 60).length; $("#staleCount").textContent = customers.filter(c => Number(c.lastContact) >= 7 && !["已成交","已流失"].includes(c.status)).length; $("#hotCount").textContent = customers.filter(c => Number(c.intent) >= 4).length; }
  function renderList() { const arr = visible(); if (!arr.length) { els.list.innerHTML = `<div class="empty-list">还没有匹配的客户。<br>可以新增一位，或载入示例数据。</div>`; return; } els.list.innerHTML = arr.map(c => { const s = score(c); return `<button class="customer-row ${c.id === selectedId ? "is-selected" : ""}" data-id="${c.id}" type="button"><span class="priority-bar ${level(s)}"></span><span class="customer-main"><span class="customer-name">${esc(c.name || "未命名客户")}</span><span class="customer-meta">${esc(c.company || "未填写公司")} · ${esc(c.status || "待联系")}</span></span><span class="customer-side"><span class="score">${s}</span><span class="status-label">${Number(c.lastContact || 0)}天前</span></span></button>`; }).join(""); }
  function advice(c) { const days = Number(c.lastContact || 0); if (c.status === "已成交") return ["保持服务联系", "订单已成交，建议记录交付节点并安排回访。", "成交客户"];
    if (c.status === "已流失") return ["归档并保留复盘记录", "当前客户已标记为流失，不建议继续投入高频跟进。", "已流失"];
    if (c.status === "无回复" || days >= 7) return ["重新激活一次沟通", `已经 ${days} 天没有联系，可以带着一个具体的新信息再次触达，而不是只问“考虑得怎么样”。`, "长时间未回复"];
    if (c.status === "已报价") return ["先确认价格异议的来源", "先区分预算、配置、交付和竞品差异，再决定是否调整方案或报价。", "报价后跟进"];
    if (c.status === "谈判中") return ["围绕决策条件推进", "客户已进入谈判阶段，建议确认决策人、时间表和最后一个阻力点。", "谈判推进"];
    if (c.status === "需求确认") return ["补齐需求与采购时间", "当前需求较明确，下一步把使用场景、采购节点和验收标准问清楚。", "需求确认"];
    return ["完成第一次有效沟通", "先了解客户场景、预算和决策时间，再决定是否进入方案阶段。", "待联系"];
  }
  function script(c) { const a = advice(c)[0]; if (c.status === "无回复" || Number(c.lastContact || 0) >= 7) return `${c.name || "您好"}，上次给您发的${c.need || "方案"}我这边补充了一点信息：如果您方便，我想结合${c.company || "贵司"}目前的使用场景，帮您把重点再梳理一下。您这周哪天比较方便？`; if (c.status === "已报价") return `${c.name || "您好"}，想再跟您确认一下，当前主要是整体预算需要控制，还是这套配置超出了预期？如果方便，我可以根据实际使用场景帮您调整一个更合适的方案。`; if (c.status === "需求确认") return `${c.name || "您好"}，为了把${c.need || "需求"}方案做得更准确，想和您确认一下预计采购时间、使用规模以及验收时最看重的指标，您看什么时候方便沟通？`; return `${c.name || "您好"}，关于${c.need || "这个需求"}，我想先了解一下您目前最希望解决的问题和预计时间，再给您一个合适的建议。您方便简单聊两句吗？`; }
  function renderDetail() { const c = customers.find(x => x.id === selectedId); if (!c) { els.empty.classList.remove("is-hidden"); els.detail.classList.add("is-hidden"); return; } els.empty.classList.add("is-hidden"); els.detail.classList.remove("is-hidden"); const s = score(c), a = advice(c); $("#detailName").textContent = c.name || "未命名客户"; $("#detailCompany").textContent = `${c.company || "未填写公司"} · ${c.need || "未填写需求"}`; const chip = $("#detailPriority"); chip.textContent = `${priority(s)} · ${s}/100`; chip.className = `priority-chip ${level(s)}`; $("#detailStatus").textContent = a[2]; $("#detailStatusHint").textContent = c.status || "待联系"; $("#detailIntent").textContent = stars(c.intent); $("#detailIntentHint").textContent = c.feedback || "暂无客户反馈"; $("#detailCadence").textContent = Number(c.lastContact || 0) === 0 ? "今天" : `${c.lastContact} 天前`; $("#detailCadenceHint").textContent = Number(c.lastContact || 0) >= 7 ? "建议尽快触达" : "保持正常节奏"; $("#ruleScore").textContent = `RULE SCORE ${s}`; $("#detailAdvice").textContent = a[0]; $("#detailReason").textContent = a[1]; $("#detailScript").value = script(c); ["Name","Company","Need","Budget","Status","LastContact","Intent","Feedback"].forEach(k => { const f = $("#field" + k); if (!f) return; const key = k[0].toLowerCase() + k.slice(1); f.value = c[key] ?? ""; }); }
  function render() { renderMetrics(); renderList(); renderDetail(); }
  function esc(v) { return String(v ?? "").replace(/[&<>"']/g, x => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[x])); }
  function readForm() { const c = customers.find(x => x.id === selectedId); if (!c) return null; ["name","company","need","budget","status","lastContact","intent","feedback"].forEach(k => { const f = $("#field" + k[0].toUpperCase() + k.slice(1)); if (f) c[k] = f.value; }); c.lastContact = Math.max(0, Number(c.lastContact || 0)); c.intent = Math.max(1, Math.min(5, Number(c.intent || 1))); return c; }
  function addCustomer() { const c = { id:id(), name:"新客户", company:"", need:"", budget:"", status:"待联系", feedback:"", lastContact:0, intent:3 }; customers.unshift(c); selectedId = c.id; save(); render(); setTimeout(() => $("#fieldName")?.focus(), 0); toast("已新增客户"); }
  function deleteCustomer() { if (!selectedId) return; const c = customers.find(x => x.id === selectedId); if (!c || !confirm(`确定删除“${c.name}”吗？`)) return; customers = customers.filter(x => x.id !== selectedId); selectedId = customers[0]?.id || null; save(); render(); toast("客户已删除"); }
  function loadDemo() { customers = DEMO.map(c => ({...c})); selectedId = customers[0].id; save(); render(); toast("已载入 5 条示例客户"); }
  function exportCsv() { if (!customers.length) return toast("暂无客户可导出", true); const headers = ["客户","公司","需求","预算","状态","反馈","最近联系(天)","意向(星)"]; const rows = customers.map(c => [c.name,c.company,c.need,c.budget,c.status,c.feedback,c.lastContact,c.intent]); const csv = "\ufeff" + [headers,...rows].map(row => row.map(x => `"${String(x ?? "").replaceAll('"','""')}"`).join(",")).join("\n"); const blob = new Blob([csv], {type:"text/csv;charset=utf-8"}); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "客户跟进清单.csv"; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); toast("已导出客户跟进清单"); }
  function parseCsv(text) { const lines = text.replace(/^\ufeff/, "").split(/\r?\n/).filter(Boolean); if (lines.length < 2) throw new Error("empty"); const parse = line => { const out=[]; let cur="", quote=false; for (let i=0;i<line.length;i++){const ch=line[i]; if(ch==='"' && line[i+1]==='"'){cur+='"';i++;} else if(ch==='"') quote=!quote; else if(ch===','&&!quote){out.push(cur);cur="";} else cur+=ch;} out.push(cur); return out; }; const head=parse(lines[0]); const map = key => head.findIndex(x => x.includes(key)); return lines.slice(1).map(line => { const r=parse(line); return {id:id(),name:r[map("客户")]||"未命名客户",company:r[map("公司")]||"",need:r[map("需求")]||"",budget:r[map("预算")]||"",status:r[map("状态")]||"待联系",feedback:r[map("反馈")]||"",lastContact:Number(r[map("最近联系")])||0,intent:Number(r[map("意向")])||3}; }); }
  $("#loadDemo").addEventListener("click", loadDemo); $("#clearAll").addEventListener("click", () => { if (!customers.length || confirm("确定清空本地客户数据吗？")) { customers=[]; selectedId=null; save(); render(); toast("客户数据已清空"); } }); $("#addCustomer").addEventListener("click", addCustomer); $("#deleteCustomer").addEventListener("click", deleteCustomer); $("#exportCsv").addEventListener("click", exportCsv); $("#searchInput").addEventListener("input", renderList); $("#sortSelect").addEventListener("change", renderList); $("#customerList").addEventListener("click", e => { const row=e.target.closest("[data-id]"); if(row){selectedId=row.dataset.id; render();} }); $("#saveCustomer").addEventListener("click", () => { if(readForm()){save();render();toast("客户记录已保存");} }); $("#copyScript").addEventListener("click", async () => { try { await navigator.clipboard.writeText($("#detailScript").value); toast("话术已复制"); } catch { $("#detailScript").select(); toast("请手动复制话术", true); } }); $("#csvInput").addEventListener("change", async e => { const file=e.target.files[0]; if(!file)return; try { const imported=parseCsv(await file.text()); customers=[...imported,...customers]; selectedId=imported[0]?.id||selectedId; save();render();toast(`已导入 ${imported.length} 条客户`); } catch { toast("CSV 格式无法识别，请检查首行字段", true); } e.target.value=""; });
  render();
})();
